### ISSUE TITLE
NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ykeremekinci** [rounakbanik/generative-art-nft#23]
Starting task...
Traceback (most recent call last):
  File "D:\Google Indirilenler\generative-art-nft-099c93f6cd918a124e9f6e7e044a157eee9b49bd\nft.py", line 259, in <module>
    main()
  File "D:\Google Indirilenler\generative-art-nft-099c93f6cd918a124e9f6e7e044a157eee9b49bd\nft.py", line 250, in main
    rt = generate_images(edition_name, num_avatars)
  File "D:\Google Indirilenler\generative-art-nft-099c93f6cd918a124e9f6e7e044a157eee9b49bd\nft.py", line 186, in generate_images
    if is_duplicated(rarity_dict, trait_sets, image_index):
  File "D:\Google Indirilenler\generative-art-nft-099c93f6cd918a124e9f6e7e044a157eee9b49bd\nft.py", line 151, in is_duplicated
    if rarity_dict[CONFIG[idx]['name']][index] != trait[: -1 * len('.png')]:
TypeError: 'NoneType' object is not subscriptable

I got this error. Can anybody help me?

**Comment by levintech** [comment]
Hi, @ykeremekinci Thanks for sharing your script.
I found what the issue and fixed them. I missed checking None traits mechanism on the script. I had already fixed that issue and test them on my side. You can see the updated code now. If you have any other problem, please kindly share me.
Thanks.
